<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true"
    CodeBehind="Default.aspx.cs" Inherits="SaleProject._Default" %>

<asp:Content ID="HeaderContent" runat="server" ContentPlaceHolderID="HeadContent">
    <style type="text/css">
        .style1
        {
            width: 100%;
        }
        .style2
        {
            text-align: right;
        }
    </style>
</asp:Content>
<asp:Content ID="BodyContent" runat="server" ContentPlaceHolderID="MainContent">
    <h2>
        Welcome to Sale Service</h2><table class="style1">
            <tr>
                <td style="text-align: right">
                    Enter name*</td>
                <td>
                    <asp:TextBox ID="TextBox1" runat="server" OnTextChanged="TextBox1_TextChanged"></asp:TextBox>
                </td>
                <td>
                    <asp:RequiredFieldValidator ID="reqName" runat="server" 
                        ControlToValidate="TextBox1" ErrorMessage="Please Enter Name" 
                        ValidationGroup="var"></asp:RequiredFieldValidator>
                </td>
            </tr>
            <tr>
                <td class="style2">
                    Address*</td>
                <td>
                    <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
                </td>
                <td>
                    <asp:RequiredFieldValidator ID="reqAddress" runat="server" 
                        ControlToValidate="TextBox2" ErrorMessage="Please Enter Address" 
                        ValidationGroup="var"></asp:RequiredFieldValidator>
                </td>
            </tr>
            <tr>
                <td class="style2">
                    Email ID*</td>
                <td>
                    <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
                </td>
                <td>
                    <asp:RequiredFieldValidator ID="ReqEmail" runat="server" 
                        ControlToValidate="TextBox3" ErrorMessage="Please Enter Email" 
                        ValidationGroup="var"></asp:RequiredFieldValidator>
                </td>
            </tr>
            <tr>
                <td class="style2">
                    &nbsp;</td>
                <td>
                    <asp:Button ID="Button1" runat="server" onclick="Button1_Click" Text="Save" 
                        ValidationGroup="var" />
                </td>
                <td>
                    &nbsp;</td>
            </tr>
        </table>
    
<p>
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True"  DataKeyNames="CustomerID,CustomerName"
            AllowSorting="True" AutoGenerateDeleteButton="True" 
            onrowdeleting="GridView1_RowDeleting" onsorting="GridView1_Sorting" 
          >
        </asp:GridView>
</p>
    <p>
        <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
</p>
<p>
        &nbsp;</p>
    </asp:Content>
