//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Peers()
        {
            this.DataFiles = new HashSet<DataFiles>();
        }
    
        public string PeerName { get; set; }
        public string PeerPassword { get; set; }
        public string PeerIP { get; set; }
        public int PeerPort { get; set; }
        public bool PeerIsOnline { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataFiles> DataFiles { get; set; }
    }
}
